### PR TITLE
fix: storage not working on tvOS

### LINKED ISSUE #315: Apple TV support is broken
### Version

3.2.0

### Steps to Reproduce

Despite the documentation at https://posthog.com/docs/libraries/ios stating that Apple TV is supported (from tvOS 13 onward), on actually testing this I found out that it is not in fact supported:

1. Enable debug logging (config.debug = true)
2. Launch the Apple TV app with PostHog integrated
3. Observe error messages on the debug console such as: [PostHog] Error creating storage directory: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “phc_klFZ2lyYCUw7AoMcLfZ0UOxJJPoeKKmOCLARjbYDU3Y” in the folder “REDACTED”." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/3B250B5C-54D3-4DC6-9C0B-0B21DC24327E/Library/Application Support/REDACTED/phc_klFZ2lyYCUw7AoMcLfZ0UOxJJPoeKKmOCLARjbYDU3Y, NSURL=file:///var/mobile/Containers/Data/Application/3B250B5C-54D3-4DC6-9C0B-0B21DC24327E/Library/Application%20Support/REDACTED/phc_klFZ2lyYCUw7AoMcLfZ0UOxJJPoeKKmOCLARjbYDU3Y, NSUnderlyingError=0x3021dbe10 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}

### Expected Result

I have an app that supports iOS, macOS and Apple TV from a common codebase. The PostHog integration is handled via a common manager class with minimal changes required between the 3 platforms. For iOS and macOS, everything works as expected and I can see the events on the PostHog console. However, for Apple TV, I observe zero events with the OS set to Apple TV - which is expected as the PostHog SDK cannot write to the storage folder on Apple TV.

### Actual Result

As mentioned above, error messages on the debug console such as: [PostHog] Error creating storage directory: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “phc_klFZ2lyYCUw7AoMcLfZ0UOxJJPoeKKmOCLARjbYDU3Y” in the folder “REDACTED”." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/3B250B5C-54D3-4DC6-9C0B-0B21DC24327E/Library/Application Support/REDACTED/phc_klFZ2lyYCUw7AoMcLfZ0UOxJJPoeKKmOCLARjbYDU3Y, NSURL=file:///var/mobile/Containers/Data/Application/3B250B5C-54D3-4DC6-9C0B-0B21DC24327E/Library/Application%20Support/REDACTED/phc_klFZ2lyYCUw7AoMcLfZ0UOxJJPoeKKmOCLARjbYDU3Y, NSUnderlyingError=0x3021dbe10 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}

### PR DESCRIPTION
**Pull request by ioannisj**
## :bulb: Motivation and Context

Closes #315 

Local storage support on tvOS is [limited](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppleTV_PG/), so we cannot use `Application Support` directory for storage. 
Unfortunately, the permission error is only visible when running on a physical device and not on simulators. 

This fix does the following: 
- Use `Library/Caches` for file queues
- Use lower defaults on tvOS for some SDK configs like flushAt to lower the chances of missing events

> tvOS only, other platforms should not be affected

## :green_heart: How did you test it?

Hasn't been fully tested since I don't have access to a physical device, but the user who reported this verified that switching to `Library/Caches` fixed the issue. 

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [x] No breaking change or entry added to the changelog.

### CODE REVIEW

File: PostHog/PostHogConfig.swift [hunk 1]
```diff
@@ -7,6 +7,20 @@
 import Foundation
 
 @objc(PostHogConfig) public class PostHogConfig: NSObject {
+    enum Defaults {
+        #if os(tvOS)
+            static let flushAt: Int = 5
+            static let maxQueueSize: Int = 100
+            static let maxBatchSize: Int = 5
+            static let flushIntervalSeconds: TimeInterval = 5
```
Comment (marandaneto) [inline PostHog/PostHogConfig.swift:15]: i think these 2 is fine as it is
the bigger the batch the better
the one is is a trade off of battery and resources, but we don't need more than 30s I think

File: PostHog/PostHogStorage.swift [hunk 2]
```diff
@@ -38,10 +50,18 @@ func appGroupContainerUrl(config: PostHogConfig) -> URL? {
...
+        let url = FileManager.default
+            .containerURL(forSecurityApplicationGroupIdentifier: appGroupIdentifier)?
+            .appendingPathComponent("Library/Caches/")
+            .appendingPathComponent(bundleIdentifier)
+    #else
+        let url = FileManager.default
+            .containerURL(forSecurityApplicationGroupIdentifier: appGroupIdentifier)?
+            .appendingPathComponent("Library/Application Support/")
+            .appendingPathComponent(bundleIdentifier)
+    #endif
```
Comment (marandaneto) [inline PostHog/PostHogStorage.swift:64]: this can be a method, and we just pass the `appendingPathComponent` as param, so DRY

File: PostHog/PostHogStorage.swift [hunk 3]
```diff
@@ -75,16 +95,30 @@ class PostHogStorage {
         case sessionReplay = "posthog.sessionReplay"
         case isIdentified = "posthog.isIdentified"
         case personProcessingEnabled = "posthog.enabledPersonProcessing"
+
+        var useFileStorage: Bool {
```
Comment (marandaneto) [inline PostHog/PostHogStorage.swift:99]: Not sure i follow why we need this

File: PostHog/PostHogConfig.swift [hunk 4]
```diff
@@ -7,6 +7,20 @@
 import Foundation
 
 @objc(PostHogConfig) public class PostHogConfig: NSObject {
+    enum Defaults {
+        #if os(tvOS)
+            static let flushAt: Int = 5
+            static let maxQueueSize: Int = 100
+            static let maxBatchSize: Int = 50
+            static let flushIntervalSeconds: TimeInterval = 30
```
Comment (marandaneto) [inline PostHog/PostHogConfig.swift:15]: we are repeating both, can we just let it off the if/else branch

File: PostHog/PostHogStorage.swift [hunk 5]
```diff
@@ -10,11 +10,24 @@ import Foundation
...
  */
 func applicationSupportDirectoryURL() -> URL {
-    let url = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
+    #if os(tvOS)
+        // tvOS restricts access to Application Support directory on physical devices
+        // Use Library/Caches directory which may have less frequent eviction behavior than temp (which is purged when the app quits)
+        let url = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first!
+    #else
+        let url = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
+    #endif
```
Comment (marandaneto) [inline PostHog/PostHogStorage.swift:29]: we can do similar to `librarySubPath` here
define the param with the if condition, so we don't repeat the whole `FileManager` line

File: PostHog/PostHogStorage.swift (hunk 3 above)
Comment (marandaneto) [reply PostHog/PostHogStorage.swift:99]: I think its common that the OS clears up caching whenever is needed, but I don't think its common that it clears the cache every time you exit the app, is it?
if that's not the case, I'd just use the cache always, so we don't have to have this extra logic around `useFileStorage`

Comment (marandaneto) [reply PostHog/PostHogStorage.swift:100]: I also understand that using the `UserDefaults` would help persisting the distinct id whenever this happens, if it happens, so your call here

File: PostHog/PostHogStorage.swift [hunk 6]
```diff
@@ -75,16 +95,30 @@ class PostHogStorage {
         case sessionReplay = "posthog.sessionReplay"
         case isIdentified = "posthog.isIdentified"
         case personProcessingEnabled = "posthog.enabledPersonProcessing"
+
+        var useFileStorage: Bool {
+            #if os(tvOS)
+                [.replayQeueue, .oldQeueue, .queue].contains(self)
```
Comment (marandaneto) [inline PostHog/PostHogStorage.swift:102]: i think more things should be here then because they can be heavy for user defaults (limit 500kb) eg flags, flags payloads, registerProperties, groups, we just cannot predict how much data would be because it really depends on how many flags and payloads they have ,etc

**Review by marandaneto — APPROVED** [review]
left a few suggestions and one point to discuss otherwise LGTM
