### PR TITLE
fix: reported crash on PostHogSessionManager

### LINKED ISSUE #302: Crash in PostHogSessionManager.swift
### Version

3.19.5

### Steps to Reproduce

The stack trace for the cash is like this:

Image

The code that's causing the crash is in file PostHogReplayIntegration.swift at line 158.
```
private func resetViews() {
     windowViews.removeAllObjects()
}
```

When calling `removeAllObjects` on `windowViews`, the crash occurred.

### Expected Result

No crash.

### Actual Result

Crashed.

### PR DESCRIPTION
**Pull request by ioannisj**
## :bulb: Motivation and Context

Closes #302 

Sync access to `windowViews` - looks like a crash because of concurrent access to windowViews. There is a possibility session is reset (and we try to clear windowViews) while we are generating a replay screenshot. 

Also added some fly-by synchronization locks that I feel we missed. 

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [x] No breaking change or entry added to the changelog.

### CODE REVIEW

File: PostHog/Utils/ApplicationLifecyclePublisher.swift [hunk 1]
```diff
@@ -123,9 +123,21 @@ final class ApplicationLifecyclePublisher: BaseApplicationLifecyclePublisher {
...
 
-    var didBecomeActiveCallbacks: [UUID: AppLifecycleHandler] = [:]
-    var didEnterBackgroundCallbacks: [UUID: AppLifecycleHandler] = [:]
-    var didFinishLaunchingCallbacks: [UUID: AppLifecycleHandler] = [:]
+    private var didBecomeActiveCallbacks: [UUID: AppLifecycleHandler] = [:]
+    private var didEnterBackgroundCallbacks: [UUID: AppLifecycleHandler] = [:]
+    private var didFinishLaunchingCallbacks: [UUID: AppLifecycleHandler] = [:]
+
+    var didBecomeActiveHandlers: [AppLifecycleHandler] {
+        registrationLock.withLock { Array(didBecomeActiveCallbacks.values) }
```
Comment (marandaneto) [inline PostHog/Utils/ApplicationLifecyclePublisher.swift:131]: Aren't all those handlers only called on the main thread?

**Review by marandaneto — APPROVED** [review]
