### PR TITLE
fix: use global frame on wireframe views

### LINKED ISSUE #231: Wireframe Session Recording appears mangled
### Version

3.13.3

### Steps to Reproduce

1. Added PostHog to my project
2. Enabled session recording with the default method (wireframe) and disabled masking Images.
3. Started app and Recorded some sessions 
4. Went to PostHog to view them and they're mangled.

The app is a UIKit-based app, so there shouldn't be any issues with wireframe. Maybe one of my libraries is causing the issue if it does something weird to the view hierarchy?

### Expected Result

A nice wireframe layout of my app's UI

### Actual Result

Screenshot 2024-11-05 at 9 48 22 AM

### PR DESCRIPTION
**Pull request by ioannisj**
## :bulb: Motivation and Context

Closes #231 

This issue was a bit challenging to uncover, but the solution turned out to be quite straightforward. After digging into the frontend code, I realized we always use `position: fixed` when styling nodes. To ensure the wireframe renders correctly, we need to convert all view frames to global screen coordinates.

### Before
before

### After
after

## :green_heart: How did you test it?

Locally with some sample projects

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [x] No breaking change or entry added to the changelog.

### CODE REVIEW

File: PostHog/Replay/PostHogReplayIntegration.swift [hunk 1]
```diff
@@ -146,14 +146,19 @@
             style.paddingLeft = Int(insets.left)
         }
 
-        private func createBasicWireframe(_ window: UIView) -> RRWireframe {
+        private func createBasicWireframe(_ view: UIView) -> RRWireframe {
```
Comment (marandaneto) [inline PostHog/Replay/PostHogReplayIntegration.swift:149]: the first time `toWireframe` gets called, we always pass the `window`, so maybe this method should have 2 params, the view and the window.
`view.window` returns nullable which is likely never the case, but if it does, the positioning will be broken again, passing the `view` and `window`, we know both are never nullable, similar to `findMaskableWidgets`

File: PostHog/Replay/PostHogReplayIntegration.swift [hunk 2]
```diff
@@ -447,8 +452,14 @@
                 wireframe.inputType = "button"
                 wireframe.disabled = !button.isEnabled
 
+                // UIButton has a UILabel subview that displays the button's text
+                // We want to skip visiting children if button is sensitive
+                // Otherwise, we capture the button's title through its child UILabel
```
Comment (marandaneto) [inline PostHog/Replay/PostHogReplayIntegration.swift:457]: but then we will check if the label is `isLabelSensitive` and it will mask anyway, right? confused...

Comment (marandaneto) [reply PostHog/Replay/PostHogReplayIntegration.swift:457]: maybe a better approach would be to do what we do in the `findMaskableWidgets` and `maskChildren` flag, we still traverse the children, but respect the parent's masking.
the point is that the children may have more wireframes to be laid out and we will lose the details, eg if the `font` is applied to the UILable and not the Button

File: PostHog/Utils/UIApplication+.swift [hunk 3]
```diff
@@ -26,6 +26,7 @@
                 } else {
                     // check scene.windows.isKeyWindow
                     for window in scene.windows {
+                        // swiftlint:disable:next for_where
```
Comment (marandaneto) [inline PostHog/Utils/UIApplication+.swift:29]: We use `where` in some other places already so let's just use it instead of silencing the linter.

File: PostHog/Replay/PostHogReplayIntegration.swift [hunk 4]
```diff
@@ -374,18 +379,19 @@
...
-        private func toWireframe(_ view: UIView) -> RRWireframe? {
+        private func toWireframe(_ view: UIView, isParentSensitive: Bool = false) -> RRWireframe? {
             if !view.isVisible() {
                 return nil
             }
 
             let wireframe = createBasicWireframe(view)
-
             let style = RRStyle()
+            var isSensitive = false
```
Comment (marandaneto) [inline PostHog/Replay/PostHogReplayIntegration.swift:389]: I think this should be a local var within each if block otherwise a component that extends 2+ interfaces can swap the values, not sure if this will happen but on Android it'd, eg a Button is a `Button` and also a `TextView`, so if `isSensitive=true` and `isSensitive=false` in the 2nd case, you ignored the 1st result which is isSensitive=true

File: PostHog/Replay/PostHogReplayIntegration.swift [hunk 5]
```diff
@@ -499,7 +506,7 @@
             if !view.subviews.isEmpty {
                 var childWireframes: [RRWireframe] = []
                 for subview in view.subviews {
-                    if let child = toWireframe(subview) {
+                    if let child = toWireframe(subview, isParentSensitive: isSensitive) {
```
Comment (marandaneto) [inline PostHog/Replay/PostHogReplayIntegration.swift:509]: I think this should be passed as a reference, and cleared out after all subviews, see `findMaskableWidgets`.
Right now if:
Button -> sensitive -> isSensitive=true
Label -> not sensitive -> isSensitive=false
Something else -> not sensitive -> isSensitive=false but should have respected isSensitive=true from the Button parent

Comment (marandaneto) [reply PostHog/Replay/PostHogReplayIntegration.swift:509]: I can't tell if not running the code, I know I tested `findMaskableWidgets` passing a reference + cleaning up the instance after looping the children, and I know that works.

File: PostHog/Replay/PostHogReplayIntegration.swift [hunk 6]
```diff
@@ -423,39 +429,40 @@
...
                     }
                 }
             }
 
             if let imageView = view as? UIImageView {
+                isSensitive = isImageViewSensitive(imageView)
                 wireframe.type = "image"
                 if let image = imageView.image {
-                    if !isImageViewSensitive(imageView) {
+                    if !isSensitive, !isParentSensitive {
```
Comment (marandaneto) [inline PostHog/Replay/PostHogReplayIntegration.swift:447]: Not sure this is correct as `and`? since all others are `or`.

Comment (marandaneto) [reply PostHog/Replay/PostHogReplayIntegration.swift:447]: the other thing is that `isParentSensitive` is mostly if not all, about masking text, but in this case, the image will be or not masked based on that config too.

Comment (marandaneto) [reply PostHog/Replay/PostHogReplayIntegration.swift:447]: `findMaskableWidgets` only passes the `maskChildren` flag if the view is `view.isNoCapture()`, I don't pass `maskChildren` if it's sensitive in text or image.
Every time I find a view sensitive in text or image, I return early, So I don't run into any of those problems.
I know you chose to implement it in a slightly different way, but take another look in `findMaskableWidgets` and learn from it.

Comment (marandaneto) [reply PostHog/Replay/PostHogReplayIntegration.swift:447]: I pointed to the method implementation, plus gave a few ideas, but the current implementation is different.

Comment (marandaneto) [reply PostHog/Replay/PostHogReplayIntegration.swift:447]: discussed offline, since this is out of scope, we will follow up on another PR, and get this bug fix merged first.

**Review by marandaneto — APPROVED** [review]

File: PostHog/Replay/PostHogReplayIntegration.swift [hunk 7]
```diff
@@ -448,6 +453,8 @@
                 wireframe.disabled = !button.isEnabled
 
                 if let text = button.titleLabel?.text {
+                    // NOTE: this will create a ghosting effect since text will also be captured in child UILabel
```
Comment (marandaneto) [inline PostHog/Replay/PostHogReplayIntegration.swift:456]: will create an issue

Comment (marandaneto) [reply PostHog/Replay/PostHogReplayIntegration.swift:456]: https://github.com/PostHog/posthog-ios/issues/255
