### PR TITLE
fix: improve session replay screenshot performance

### LINKED ISSUE #321: PostHog's Session Replay feature degrades Google services performance
### Description

I noticed that Google Street View and Google Maps are lagging when PostHog's session replay is active. Every time a screenshot is captured, there's a noticeable drop in frame rate that decreases the overall smoothness of Street View navigation.

I've observed that the smaller the config.sessionReplayConfig.debouncerDelay value, the less smooth the panorama becomes, so probably this is the root cause. 

Here's my configuration:

`
let config = PostHogConfig(apiKey: "", host: "https://eu.i.posthog.com")

config.captureScreenViews = false
config.captureApplicationLifecycleEvents = true
config.sessionReplay = true
config.sessionReplayConfig.screenshotMode = true
config.sessionReplayConfig.captureNetworkTelemetry = true
config.sessionReplayConfig.maskAllImages = false
config.sessionReplayConfig.maskAllTextInputs = false
config.sessionReplayConfig.debouncerDelay = 1.0
PostHogSDK.shared.setup(config)
`

I didn't experience it with SmartLook session replay.

### PR DESCRIPTION
**Pull request by ioannisj**
## :bulb: Motivation and Context

Closes #321 and possibly #571

This PR improves screenshot performance by replacing `UIGraphicsImageRenderer` with a custom and more lightweight CGContext-backed renderer.

Physical-device benchmarking and profiling on an old iPhone XR showed the UIView.toImage() path was the dominant source of UI glitches:

 - Baseline screenshot snapshots cost ~135ms on the main thread.
 - Each snapshot correlated with a >33ms frame hitch.
 - At higher snapshot rates, replay could saturate the app and drop effective frame pacing below 60fps.

### Changes
 - Adds `PostHogGraphicsImageRenderer`, a direct CoreGraphics bitmap renderer.
 - Uses it for `UIView.toImage()` screenshot capture.
 - Uses it for `RRWireframe.maskImage()` masked screenshot redraw.
 - Does not change masking traversal logic, masking decisions, serialization, or replay event structure. 

### Findings

Physical device benchmark on an iPhone XR (`iPhone11,8`), running screenshots on a complex idle view with re-layout ticks (to trigger snapshots)

Judging from the metrics collected, snapshot main-thread cost dropped by ~92%:

 | Throttle | Baseline snapshot avg | This PR snapshot avg | Delta |
 |---:|---:|---:|---:|
 | 0.50s | 134.22ms | 11.14ms | -91.7% |
 | 0.25s | 134.58ms | 10.69ms | -92.1% |
 | 0.10s | 138.92ms | 10.66ms | -92.3% |

There was also a big improvement on frame pacing and app hangs. This was also prominent when running the app, frame rate stayed at 60fps at all throttle levels (not recommended if you are reading this):

 | Throttle | Baseline frames >33ms | This PR frames >33ms |
 |---:|---:|---:|
 | 0.50s | 29 | 0 |
 | 0.25s | 57 | 0 |
 | 0.10s | 93 | 0 |
 
**Before**

https://github.com/user-attachments/assets/adc13e41-1a83-4f54-9295-c79bbfab4b65 

**After**

https://github.com/user-attachments/assets/c283d247-1b58-4eb9-9818-5326b411ae9c

### Post-release

- [ ] Bump RN posthog-ios min version
- [ ] Bump Flutter posthog-ios min version

### Note

We previously experimented with using a custom renderer to improve performance. Back then, the timing results were not that convincing and I decided not to ship a fix, which was the wrong call. This could be because: 
- I had the wrong approach on profiling the improvement and baseline
- I was not profiling/testing on the correct device 

This one is on me because we could have shipped this improvement much earlier!

## :green_heart: How did you test it?

- Profiling with Xcode Instruments and custom benchmarking
- Running on a lower-end physical device
- Verified that session recordings are scaled and masked correctly in the PostHog UI
- This 👇 
 

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [ ] No breaking change or entry added to the changelog.

## If releasing new changes

- [x] Ran `pnpm changeset` to generate a changeset file
- [x] Added the `release` label to the PR

### CODE REVIEW

File: PostHog/Replay/UIView+Util.swift [hunk 1]
```diff
@@ -36,22 +36,17 @@
         }
 
         func toImage() -> UIImage? {
-            // Avoid Rendering Offscreen Views
-            let bounds = superview?.bounds ?? bounds
-            let size = bounds.intersection(bounds).size
```
Comment (ioannisj) [inline PostHog/Replay/UIView+Util.swift:41]: Unrelated change but:
1. this is always called on a UIWindow, and superview here will always be null
2. bounds.intersection(bounds).size will always be bounds.size

**Review by marandaneto — APPROVED** [review]
