### PR TITLE
fix: iOS26 session replay masking

### LINKED ISSUE #408: Session replay masking seems to be broken on iOS 26+
### Description

Some recordings seem to ignore the global masking config on iOS 26. 

Ticket: https://posthoghelp.zendesk.com/agent/tickets/44565

### PR DESCRIPTION
**Pull request by ioannisj**
## :bulb: Motivation and Context

Closes #408 

Docs PR: https://github.com/PostHog/posthog.com/pull/14088

Updates the session replay masking logic to handle SwiftUI behavior changes introduced with the iOS 26 + Xcode 26 and the new SwiftUI rendering engine, where some SwiftUI primitives are rendered as `CALayer` sublayers rather than predictable backing `UIViews`

I could not find a better alternative other than iterating over each view's sublayers to find SwiftUI maskable views. This is limited to iOS 26+ but could potentially have a performance hit for complex hierarchies. 

Note: Because SwiftUI primitive views are now host-less, our approach with `.postHogMask()` and `.postHogNoMask()` is broken as well. I dropped some comments in the code but I'll follow up with a docs update to note this + a fresh issue to track

## :green_heart: How did you test it?

Manually with sample projects

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [x] No breaking change or entry added to the changelog.

### CODE REVIEW

File: PostHog/Replay/PostHogReplayIntegration.swift [hunk 1]
```diff
@@ -512,6 +525,31 @@
...
+            //
+            // Note: prior to iOS 26, primitive views like Text, Image, Button were drawn
+            // inside a host view (subclass of UIView), however starting iOS 26 this seems
+            // to no longer be the case and all SwiftUI primitives seem to be somehow drawn
+            // without an underlying UIView host view (but as sublayers of other parent views).
+            //
+            // I could not find a consistent pattern to limit this layer search approach,
+            // so for iOS 26 we'll need to iterate over the view's sublayers as well to find maskable elements.
+            if #available(iOS 26.0, *) {
+                for layer in view.layer.sublayers ?? [] {
```
Comment (pauldambra) [inline PostHog/Replay/PostHogReplayIntegration.swift]: am assuming we don't need to recurse in and find sublayers of `layer`

Comment (ioannisj) [reply PostHog/Replay/PostHogReplayIntegration.swift]: Empirically, this seems to catch all the SwiftUI primitive views. They appear to be added only as direct sublayers to views, but there's no official documentation on how this works internally. Testing on some sample apps, this seems to do the trick. I'd prefer to roll out with this single level scan and see how it works in the wild? Hope we won't have to scan deeper than this

Comment (ioannisj) [reply PostHog/Replay/PostHogReplayIntegration.swift]: @pauldambra I was wrong, your comment made me look twice. Checked with a more complex UI hierarchy and indeed we do need to recurse here. thanx
