### PR TITLE
fix: view masking when using clipShape view modifier

### LINKED ISSUE #296: Session Replay Mask text forces parent element to mask everything
### Version

3.19.4

### Steps to Reproduce

1. Mask a Text() element using `.postHogMask()`
2. The text element is inside a parent element which acts like a list item View
3. if the parent element has the `.clipShare` modifier, the whole element gets masked instead of just the text

### Expected Result

The inner Text view should be masked

Image

### Actual Result

The whole list item gets Masked

Image

### PR DESCRIPTION
**Pull request by ioannisj**
## :bulb: Motivation and Context

Closes #296 

`.clipShape` and `.clipped` SwiftUI view modifiers seem to be injecting a `SwiftUI._UIInheritedView` to the view hierarchy that has the size of the view (the parent view when masking in this case) 

When we manually tag views with `postHogNoCapture` in `postHogMask()` modifier, we were also tagging this wrapper view as well, which was then being masked by session replay. 

Current fix is to ignore `SwiftUI._UIInheritedView` types in postHogMask(). Future improvements to session replay could include testing if a view has visual impact before deciding to mask or visit children

| Before  | After   |  
|------|-----|
| |  |

## :green_heart: How did you test it?

Local sample project

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [x] No breaking change or entry added to the changelog.

### CODE REVIEW

File: PostHog/SwiftUI/PostHogTagViewModifier.swift [hunk 1]
```diff
@@ -175,7 +184,15 @@
 
         return commonAncestor
             .allDescendants(between: anchorView, and: taggerView)
-            .filter { !$0.postHogView } // exclude injected views
+            .lazy
```
Comment (marandaneto) [inline PostHog/SwiftUI/PostHogTagViewModifier.swift:187]: what does lazy here do? we did not need before

**Review by marandaneto — APPROVED** [review]

File: PostHog/SwiftUI/PostHogTagViewModifier.swift (hunk 1 above)
Comment (marandaneto) [reply PostHog/SwiftUI/PostHogTagViewModifier.swift:187]: Oh nice, TIL, your call here.
The && is more readable but less functional so you can decide :)
