### PR TITLE
fix: prevent crashes from non JSON-serializable property types

### LINKED ISSUE #460: Crash in getPersonPropertiesHash when userProperties contains Date objects (v3.40.0)
## Description

After updating from PostHog iOS SDK 3.37.0 to 3.40.0, the app crashes immediately on launch with `NSInvalidArgumentException: Invalid type in JSON write (__NSTaggedDate)`.

## Environment

- **PostHog iOS SDK version**: 3.40.0 (works fine on 3.37.0)
- **iOS version**: iOS 18.x
- **Xcode version**: 16.x
- **Swift version**: 5.9+

## Crash Log

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (__NSTaggedDate)'
*** First throw call stack:
(0x19db94964 0x19aaa9814 0x19b14fc88 0x19b1d4628 0x19b1d7e3c 0x19b1d4628 0x19b1d7e3c 0x19bb4849c 0x19bb49448 ...)
```

## Root Cause

The crash occurs in the new `getPersonPropertiesHash()` function introduced in 3.40.0 (around line 630 in `PostHogSDK.swift`):

```swift
private func getPersonPropertiesHash(
    distinctId: String,
    userPropertiesToSet: [String: Any]?,
    userPropertiesToSetOnce: [String: Any]?
) -> String {
    var hashData: [String: Any] = ["distinct_id": distinctId]

    if let userPropertiesToSet {
        hashData["userPropertiesToSet"] = userPropertiesToSet
    }
    if let userPropertiesToSetOnce {
        hashData["userPropertiesToSetOnce"] = userPropertiesToSetOnce
    }

    // CRASH HERE: JSONSerialization cannot serialize Date objects
    if let jsonData = try? JSONSerialization.data(withJSONObject: hashData, options: [.sortedKeys]),
       let jsonString = String(data: jsonData, encoding: .utf8)
    {
        return jsonString
    }

    // fallback
    return hashData.description
}
```

`JSONSerialization.data(withJSONObject:)` throws an exception when the dictionary contains `Date` objects (or other non-JSON-serializable types like `Data`, custom objects, etc.).

## Steps to Reproduce

1. Update PostHog iOS SDK from 3.37.0 to 3.40.0
2. Call `identify()` or `setPersonProperties()` with a `Date` value in the properties dictionary:
   ```swift
   PostHogSDK.shared.identify("user123", userProperties: [
       "last_login": Date()  // This causes the crash
   ])
   ```
3. App crashes immediately

## Suggested Fix

The `getPersonPropertiesHash` function should sanitize the dictionary before attempting JSON serialization, similar to how other parts of the SDK handle this. Options:

**Option 1**: Use the existing `sanitizeDictionary()` function before serialization:
```swift
private func getPersonPropertiesHash(...) -> String {
    var hashData: [String: Any] = ["distinct_id": distinctId]

    if let userPropertiesToSet {
        hashData["userPropertiesToSet"] = sanitizeDictionary(userPropertiesToSet) ?? [:]
    }
    if let userPropertiesToSetOnce {
        hashData["userPropertiesToSetOnce"] = sanitizeDictionary(userPropertiesToSetOnce) ?? [:]
    }
    // ... rest of function
}
```

**Option 2**: Wrap the JSON serialization in a do-catch and handle the error gracefully:
```swift
do {
    let jsonData = try JSONSerialization.data(withJSONObject: hashData, options: [.sortedKeys])
    if let jsonString = String(data: jsonData, encoding: .utf8) {
        return jsonString
    }
} catch {
    hedgeLog("Failed to serialize person properties for hash: \(error)")
}
return hashData.description
```

## Workaround

Downgrade to PostHog iOS SDK 3.37.0 until this is fixed.

## Related

This was introduced in the `setPersonProperties` feature added in v3.40.0 (PR #455 or related).

### PR DESCRIPTION
**Pull request by ioannisj**
## :bulb: Motivation and Context
Closes #460

Add `toJSONData()` utilities that sanitizes dictionaries before JSON serialization.

Handles Date, URL, Data, UUID  and other non-JSON types by converting or dropping them gracefully instead of crashing.

Also fixed an existing issue with failing to sanitize infinity/NaN values which caused a crash discovered with the new unit tests added.
 
- Add toJSONData()
- Fix isValidObject() to reject Double.infinity, NaN, and CGFloat variants
- Update JSON serialization in PostHogSDK, PostHogQueue, PostHogApi
- Fixed some places I spotted where we force-unwrapped data!

## :green_heart: How did you test it?

- Added unit tests

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [x] No breaking change or entry added to the changelog.

### CODE REVIEW

File: PostHog/PostHogApi.swift [hunk 1]
```diff
@@ -94,18 +94,14 @@ class PostHogApi {
...
         ]
 
-        var data: Data?
-
-        do {
-            data = try JSONSerialization.data(withJSONObject: toSend)
-        } catch {
-            hedgeLog("Error parsing the batch body: \(error)")
-            return completion(PostHogBatchUploadInfo(statusCode: nil, error: error))
+        guard let data = toJSONData(toSend) else {
```
Comment (marandaneto) [inline PostHog/PostHogApi.swift]: arent the events props already normalized at this point? arent we doing this again?

Comment (ioannisj) [reply PostHog/PostHogApi.swift]: Yeah correct, this would be redundant. My thinking is that we add some properties right above, but that's internal and something we control. I'll revert

Comment (ioannisj) [reply PostHog/PostHogApi.swift]: Fixed

File: PostHogTests/PostHogPropertiesSerializationTest.swift [hunk 2]
```diff
@@ -0,0 +1,346 @@
...
+        @Test("setGroupPropertiesForFlags with property type", arguments: propertyPayloads)
+        func setGroupPropertiesForFlagsWithPropertyType(_ payload: PropertyTestCase) async throws {
+            let sut = getSut()
+
+            sut.setGroupPropertiesForFlags("company", properties: payload.properties(), reloadFeatureFlags: false)
+
+            sut.reset()
+            sut.close()
+        }
+    }
```
Comment (marandaneto) [inline PostHogTests/PostHogPropertiesSerializationTest.swift:268]: what those 2 tests do? what do they assert?

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,7 +1,11 @@
 ## Next
 
+- fix: prevent crashes from non JSON-serializable property types (Date, URL, Data, infinity, NaN, etc.) ([#466](https://github.com/PostHog/posthog-ios/pull/466))
+
 ## 3.40.0 - 2026-02-05
 
+> ⚠️ **Warning**: This version contains a crash when using `setPersonProperties` with non-JSON-serializable types like `Date` in properties. Please upgrade to the next version.
```
Comment (marandaneto) [inline CHANGELOG.md:8]: also add this to the GH release notes

File: PostHogTests/PostHogPropertiesSerializationTest.swift (hunk 2 above)
Comment (ioannisj) [reply PostHogTests/PostHogPropertiesSerializationTest.swift:268]: These just assert that calling these methods will not crash when the properties are serialized. Swift testing will automatically create a test case for each argument passed `propertyPayloads` in our case. I'll leave a comment here to clarify
