### PR TITLE
fix: detect and mask SwiftUI Text vs Image

### LINKED ISSUE #163: SwiftUI Text view to be detected as a `SwiftUI Image` view
### Description

This means that it'll be automatically masked if `maskAllImages` is set to `true`, even if the `maskAllTextInputs` is disabled

See note https://posthog.com/docs/session-replay/ios

### PR DESCRIPTION
**Pull request by ioannisj**
## :bulb: Motivation and Context

Closes #163 

Small refactor to distinguish between SwiftUI `Image` and `Text`

docs: https://github.com/PostHog/posthog.com/pull/9921

```swift
config.sessionReplayConfig.maskAllTextInputs = true
config.sessionReplayConfig.maskAllImages = false
```

CleanShot 2024-11-19 at 14 54 29@2x

```swift
config.sessionReplayConfig.maskAllTextInputs = false
config.sessionReplayConfig.maskAllImages = true
```
CleanShot 2024-11-19 at 14 52 13@2x

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [x] No breaking change or entry added to the changelog.

### CODE REVIEW

File: PostHog/Replay/PostHogReplayIntegration.swift [hunk 1]
```diff
@@ -21,14 +21,64 @@
         private let urlInterceptor: URLSessionInterceptor
         private var sessionSwizzler: URLSessionSwizzler?
 
-        // SwiftUI image types
-        // https://stackoverflow.com/questions/57554590/how-to-get-all-the-subviews-of-a-window-or-view-in-latest-swiftui-app
-        // https://stackoverflow.com/questions/58336045/how-to-detect-swiftui-usage-programmatically-in-an-ios-application
-        private let swiftUIImageTypes = ["SwiftUI._UIGraphicsView",
-                                         "SwiftUI.ImageLayer"].compactMap { NSClassFromString($0) }
-
-        private let swiftUIGenericTypes = ["_TtCOCV7SwiftUI11DisplayList11ViewUpdater8Platform13CGDrawingView",
```
Comment (marandaneto) [inline PostHog/Replay/PostHogReplayIntegration.swift:30]: this is not used anymore, is that intentional?

File: PostHog/Replay/PostHogReplayIntegration.swift [hunk 2]
```diff
@@ -21,14 +21,64 @@
         private let urlInterceptor: URLSessionInterceptor
         private var sessionSwizzler: URLSessionSwizzler?
 
-        // SwiftUI image types
-        // https://stackoverflow.com/questions/57554590/how-to-get-all-the-subviews-of-a-window-or-view-in-latest-swiftui-app
-        // https://stackoverflow.com/questions/58336045/how-to-detect-swiftui-usage-programmatically-in-an-ios-application
-        private let swiftUIImageTypes = ["SwiftUI._UIGraphicsView",
```
Comment (marandaneto) [inline PostHog/Replay/PostHogReplayIntegration.swift:27]: this is not used anymore, is that intentional?

File: PostHog/Replay/PostHogReplayIntegration.swift [hunk 3]
```diff
@@ -359,13 +423,9 @@
...
         private func isSwiftUIImageSensitive(_ view: UIView) -> Bool {
-            // the raw type _UIGraphicsView is always something like Color.white or similar
-            // never contains PII and should not be masked
-            // Button will fall in this case case but Button has subviews
-            let type = type(of: view)
-
-            let rawGraphicsView = String(describing: type) == "_UIGraphicsView"
-            return (config.sessionReplayConfig.maskAllImages || view.isNoCapture()) && !rawGraphicsView
+            // No way of checking if this is an asset image or not
+            // No way of checking if there's actual content in the image or not
```
Comment (marandaneto) [inline PostHog/Replay/PostHogReplayIntegration.swift:427]: the previous check was working before, I recall testing this, so why isn't it anymore?

File: PostHogExample/Assets.xcassets/max_static.imageset/Contents.json [hunk 4]
```diff
@@ -0,0 +1,12 @@
+{
+  "images" : [
+    {
+      "filename" : "max_static.png",
```
Comment (marandaneto) [inline PostHogExample/Assets.xcassets/max_static.imageset/Contents.json:4]: noice

**Comment by marandaneto** [comment]
once this is merged/released, we can remove the mentions of this issue https://github.com/PostHog/posthog-ios/issues/163 on the docs https://github.com/search?q=repo%3APostHog%2Fposthog.com+https%3A%2F%2Fgithub.com%2FPostHog%2Fposthog-ios%2Fissues%2F163&type=code

**Review by marandaneto — APPROVED** [review]
VERY NICE BUG FIX LETS GET THIS MERGED ASAP :D thanks!
