### PR TITLE
fix: safely convert floats to int

### LINKED ISSUE #293: Crash on iPad using sessionReplay = true
### Version

3.19.1

### Steps to Reproduce

1. App with tab bar and switui home
2. Init PostHog with config.sessionReplay = true
3. Got a crash at app launch

### Expected Result

No crash at all

### Actual Result

Crash at
File: PostHogReplayIntegration.swift
Line: 635
Reason: Thread 1: Swift runtime failure: Double value cannot be converted to Int because it is either infinite or NaN

Image

### PR DESCRIPTION
**Pull request by ioannisj**
## :bulb: Motivation and Context

Closes #293 

## :green_heart: How did you test it?

```
let nanNumber = NSNumber(value: CGFloat.nan) // NaN
let frNumber = NSNumber(value: CGFloat(4.5)) // 4.1
let gfmNumber = NSNumber(value: CGFloat.greatestFiniteMagnitude) // 1.797693134862316E+308

nanNumber.intValue // 0
gfmNumber.intValue // Int.max (9,223,372,036,854,775,807)
frNumber.intValue // 4
```

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [x] No breaking change or entry added to the changelog.

### CODE REVIEW

File: PostHog/Replay/Float+.swift [hunk 1]
```diff
@@ -0,0 +1,18 @@
+//
+//  Float+.swift
```
Comment (marandaneto) [inline PostHog/Replay/Float+.swift:2]: all other files are called `Name+Util.swift, should we keep the pattern?

**Comment by marandaneto** [comment]
the unit tests could be part of the tests instead of the PR description :)
