### PR TITLE
Fix/queue pending feature flags reload

### LINKED ISSUE #456: Feature flag experience continuity bug (iOS, Android, Flutter, likely React Native)
Ticket: https://posthoghelp.zendesk.com/agent/tickets/45321
 
> Users get re-bucketed after identify() despite "Persist flag across authentication" being enabled.
>
> There seems to be a race condition: when preloadFeatureFlags (default: true) is in flight and user calls identify(), the subsequent reloadFeatureFlags() is dropped instead of queued.
>
> iOS - [PostHogRemoteConfig.swift:266-271](https://github.com/PostHog/posthog-ios/blob/main/PostHog/PostHogRemoteConfig.swift#L266-L271)
> Android - [PostHogRemoteConfig.kt:341-344](https://github.com/PostHog/posthog-android/blob/main/posthog/src/main/java/com/posthog/internal/PostHogRemoteConfig.kt#L341-L344)
>
>Both have:
>
>``` 
>if loadingFeatureFlags {
>    return  // ← Dropped, never sends $anon_distinct_id
>}
>```
>
> First request completes without $anon_distinct_id → server never stores hash key override → user re-bucketed.
>
> A potential fix is to queue pending reload instead of dropping:
> 
> ``` 
> if loadingFeatureFlags {
>    pendingFlagsReload = true  // ← Queue it
>   return
>}
>// After request completes, check pendingFlagsReload and retry
>```

- [ ] iOS
- [ ] Android
- [ ] Flutter (bump min native versions when completed)
- [ ] React Native

### PR DESCRIPTION
**Pull request by ordehi**
## :bulb: Motivation and Context

When preloadFeatureFlags is enabled (the default) and identify() is called shortly after SDK init, the flag reload triggered by identify() races with the preload request. The NSLock.withLock guard in loadFeatureFlags() uses return inside the closure, which only exits the closure (not the enclosing function), so both requests fire concurrently. The anonymous-context response can then overwrite the correct identified-context response.

The same broken guard pattern also exists in reloadRemoteConfig().

This was fixed in posthog-android 3.31.0 (https://github.com/PostHog/posthog-android/pull/407). The iOS SDK remains unfixed.

Fixes #456

## :green_heart: How did you test it?

- Added 6 unit tests covering: guard prevents concurrent requests, pending request preserves correct identity context, latest pending replaces earlier ones (replaced callback fires with nil), callbacks fire for both initial and pending requests, single call has no pending queue, and reloadRemoteConfig guard works correctly
- All tests pass via make test filter=PostHogRemoteConfigTest (13/13)
- Added a debug-only "Test preload+identify race" button to the example app for manual verification. With debug = true, console shows two sequential /flags requests where the second uses the identified distinct_id

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [x] No breaking change or entry added to the changelog.

## If releasing new changes

- [x] Ran `pnpm changeset` to generate a changeset file
- [x] Added the `release` label to the PR

### CODE REVIEW

File: PostHog/PostHogRemoteConfig.swift [hunk 1]
```diff
@@ -263,11 +268,27 @@ class PostHogRemoteConfig {
...
+                    anonymousId: anonymousId,
+                    groups: groups,
+                    callback: callback
+                )
+                return prev
+            }
+            let cached = featureFlagsLock.withLock { getCachedFeatureFlags() }
+            previousCallback?(cached)
+            return
         }
```
Comment (dustinbyrne) [inline PostHog/PostHogRemoteConfig.swift]: The gap is quite narrow, but re-acquiring the lock here looks like it could introduce a race condition:

- Thread A acquires lock, sees `loadingFeatureFlags = true`, releases lock, `alreadyLoading = true`
- Thread B (the one that's loading) finishes, API callback runs, calls `notifyFeatureFlagsAndRelease` which atomically sets `loadingFeatureFlags = false` and reads `pendingFeatureFlagsRequest` as nil
- Thread A acquires lock, sets `pendingFeatureFlagsRequest`, and this request is now orphaned

```suggestion
        let (alreadyLoading, previousCallback): (Bool, (([String: Any]?) -> Void)?) = loadingFeatureFlagsLock.withLock {
            if self.loadingFeatureFlags {
                let prev = self.pendingFeatureFlagsRequest?.callback
                self.pendingFeatureFlagsRequest = PendingFeatureFlagsRequest(
                    distinctId: distinctId,
                    anonymousId: anonymousId,
                    groups: groups,
                    callback: callback
                )
                return (true, prev)
            }
            self.loadingFeatureFlags = true
            return (false, nil)
        }
        if alreadyLoading {
            let cached = featureFlagsLock.withLock { getCachedFeatureFlags() }
            previousCallback?(cached)
            return
        }
```

Comment (ordehi) [reply PostHog/PostHogRemoteConfig.swift]: Not letting me commit the suggestion, so will do this locally: "Applying suggestions on deleted lines is currently not supported."
