### PR TITLE
fix: custom host with a path

### LINKED ISSUE #274: Requested URL is incorrect when PostHog host includes a path
### Version

3.17.0

### Steps to Reproduce

See https://github.com/PostHog/posthog-flutter/issues/128

1. Set `com.posthog.posthog.POSTHOG_HOST` to `http://localhost:3000/some/path`
2. Run a dummy server on port `3000` which logs incoming requests
3. Trigger a batch of events to be sent
4. Observe that the requested URL is `http://localhost:3000/batch`

### Expected Result

The requested URL is `http://localhost:3000/some/path/batch`

### Actual Result

The requested URL is `http://localhost:3000/batch`

### PR DESCRIPTION
**Pull request by ioannisj**
## :bulb: Motivation and Context

Closes #274 

## :green_heart: How did you test it?

Added some unit tests

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [x] No breaking change or entry added to the changelog.

### CODE REVIEW

File: PostHogTests/PostHogApiTest.swift [hunk 1]
```diff
@@ -0,0 +1,206 @@
...
+        @Test("with host containing path")
+        func testHostWithPath() async throws {
+            let config = PostHogConfig(apiKey: "test_key", host: "http://localhost/api/v1")
+            let sut = PostHogApi(config)
+
+            let resp = await getApiResponse { completion in
+                sut.batch(events: [], completion: completion)
+            }
+
+            #expect(resp.statusCode == 200)
```
Comment (pauldambra) [inline PostHogTests/PostHogApiTest.swift:76]:
```suggestion
	    #expect(resp.error == nil)
            #expect(resp.statusCode == 200)
```

**Review by pauldambra — APPROVED** [review]
lots of tests 👍

**Review by marandaneto — APPROVED** [review]
left a suggestion but overall looks gooood

**Comment by bcheidemann** [comment]
@ioannisj guessing I can close https://github.com/bcheidemann-kmbal/posthog-ios/pull/1 as this PR does (near enough) the same thing?

**Comment by bcheidemann** [comment]
> > @ioannisj guessing I can close [bcheidemann-kmbal#1](https://github.com/bcheidemann-kmbal/posthog-ios/pull/1) as this PR does (near enough) the same thing?
> 
> > 
> 
> > EDIT: I see I raised the PR against a fork anyway 🙈
> 
> 
> 
> Hey @bcheidemann, so sorry! I completely missed that and didn't see a notification! That's a pity, cause it was looks like most (if not all) of the work was already done for this! 
> 
> 
> 
> Yeah, I think that the fact that it was not against this repo had something to do with it! Thank you for the effort and time though! ❤️

Hey, no problem! Very much my fault for not raising the PR against the right repo. TBH I'm glad to have another implementation of the same fix; reviewing it was a good learning opportunity for me 😉
